
permalink: pretty

exclude:
  - CNAME
  - README
  - rakefile
  - node_modules
  - package.json
  - webpack.config.js
  - webpack

keep_files:
  - .git
  - .gitignore
  - .nojekyll
  - CNAME
  - README

defaults:
  - scope:
      path: ""
      type: locations
    values:
      layout: location-details
      classname: location-details
      color: lime
  - scope:
      path: ""
      type: community-garden
    values:
      layout: location-details
      classname: location-details community-garden
      color: lime
  - scope:
      path: ""
      type: farmers-market
    values:
      layout: location-details
      classname: location-details farmers-market
      color: strawberry
  - scope:
      path: ""
      type: food-pantry
    values:
      layout: location-details
      classname: location-details food-pantry
      color: canteloupe
  - scope:
      path: ""
      type: summer-lunch
    values:
      layout: location-details
      classname: location-details summer-lunch
      color: canteloupe
  - scope:
      path: ""
      type: supermarket
    values:
      layout: location-details
      classname: location-details supermarket
      color: strawberry
  - scope:
      path: ""
      type: cultivate-la
    values:
      layout: location-details
      classname: location-details community-garden
      color: lime

collections:
  locations:
    output: true
    permalink: /locations/:path/
  community-garden:
    output: true
    permalink: /community-garden/:path/
  farmers-market:
    output: true
    permalink: /farmers-market/:path/
  food-pantry:
    output: true
    permalink: /food-pantry/:path/
  summer-lunch:
    output: true
    permalink: /summer-lunch/:path/
  supermarket:
    output: true
    permalink: /supermarket/:path/
  cultivate-la:
    output: true
    permalink: /cultivate-la/:path/
