
# This file should be about the sames as “_config.yml”, but skips the “collections”, for faster rendering.

permalink: pretty

exclude:
  - CNAME
  - README
  - rakefile
  - node_modules
  - package.json
  - webpack.config.js
  - webpack
  - api
  - locations
  - community-garden
  - farmers-market
  - food-pantry
  - summer-lunch
  - supermarket
  - cultivate-la
  - sitemap.xml
  - _community-garden
  - _farmers-market
  - _food-pantry
  - _locations
  - _node
  - _summer-lunch
  - _supermarket

keep_files:
  - .git
  - .gitignore
  - .nojekyll
  - CNAME
  - README
  - api
  - locations
  - community-garden
  - farmers-market
  - food-pantry
  - summer-lunch
  - supermarket
  - cultivate-la
  - sitemap.xml
